socket:
  server:
    debug: false
    port: 18000
    enabledTcp: true                                         #是否启用tcp
    enabledScheduledFlush: true                             # 开启定时器flush
    scheduledFlushMs: 10                                    #定时调用flush的频率单位是ms
    enabledWebSocket: true                                  #是否启用websocket
    webSocketPrefix: "/ws"                                   #websocket前缀
    maxAggregatorLength: 64                                  #聚合器最大长度 单位MB
    maxFrameBytes: -1                                        #单个消息最大长度
    maxFrameLength: -1                                       #一秒钟接收消息最大数量
    sslProtocolType: TLS                                     #ssll类型
    sslKeyStorePath: "jks/wxdtest-1.8.jks"                   #jks证书路径
    sslPasswordPath: "jks/wxdtest-1.8.jks.pwd"               #jks证书密码路径
    idleTimeout: 0
    writeTimeout: 0
    readTimeout: 0
    recvByteBufM: 12                                          #接收缓冲区大小 单位MB
    writeByteBufM: 12                                         #发送缓冲区大小 单位MB
  client:
    debug: false
    host: 127.0.0.1
    port: 18000
    connectTimeout: 500                                       #创建链接的超时时间
    enabledScheduledFlush: true                             # 开启定时器flush
    scheduledFlushMs: 10                                    #定时调用flush的频率单位是ms
    enabledWebSocket: true                                    #是否启用websocket
    webSocketPrefix: "/ws"                                    #websocket前缀
    enabledReconnection: true                                  #是否启用重连
    enabledSSL: true
    maxAggregatorLength: 64                                    #聚合器最大长度 单位MB
    maxConnectionCount: 1
    maxFrameBytes: -1                                          #单个消息最大长度
    maxFrameLength: -1                                         #一秒钟接收消息最大数量
    sslProtocolType: TLS                                       #ssll类型
    sslKeyStorePath: ""                                        #jks证书路径
    sslPasswordPath: ""                                        #jks证书密码路径
    idleTimeout: 0
    writeTimeout: 0
    readTimeout: 0
    recvByteBufM: 12                                           #接收缓冲区大小 单位MB
    writeByteBufM: 12                                          #发送缓冲区大小 单位MB