spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jdbc:
    config:
      driver-class-name: org.postgresql.Driver
      #      url: jdbc:postgresql://192.168.137.10:5432/test?stringtype=unspecified #参数的含义是把json当作字符串用
      url: jdbc:postgresql://192.168.137.10:5432/test
      #      url: jdbc:postgresql://192.168.137.15:5432/test
      username: postgres
      password: test
      show-sql: false
      ddl-auto: "update"
      packageNames: wxdgaming.game.test.entity
