sid: 1
server:
  port: 18801   #端口号
  undertow: #替代tomcat配置
    threads:
      io: 1
      worker: 200 #任务线程池
    buffer-size: 1024 #每个块的大小
    direct-buffers: true #直接内存
executor:
  basic:
    coreSize: 2           #核心线程数
    maxSize: 2           #最大线程数
    maxQueueSize: 10000   #队列数量
  logic:
    coreSize: 8           #核心线程数
    maxSize: 32           #最大线程数
    maxQueueSize: 10000   #队列数量
  virtual:
    coreSize: 100           #核心线程数
    maxSize: 200           #最大线程数
    maxQueueSize: 10000   #队列数量
http:
  client:
    core: 20                            #连接池的核心连接数
    max: 300                            #连接池的最大连接数
    resetTimeM: 30                      #连接池重置时间，时间太长连接池会异常 单位分钟
    sslProtocol: TLS                    #ssl 类型
    connectTimeOut: 3000                #创建连接超时时间
    connectionRequestTimeout: 1000      #从连接池获取连接超时
    keepAliveTimeout: 30000             #连接有效时间
    readTimeout: 3000                   #读取超时时间
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: pgsql,socket
  web:
    resources:
      add-mappings: true
      static-locations: file:public/,file:upload/,classpath:/public/
      chain:
        compressed: true    #开启压缩
        enabled: true       #开启
        cache: true         #开启缓存
      cache:
        period: 186400      # 缓存一天
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false                            # 是否开启缓存默认为true
    prefix: classpath:/templates/           #设置thymeleaf路径默认为src/main/resources/templates
    suffix: .html                           # 设置thymeleaf模板后缀
    content-type: text/html
    mode: LEGACYHTML5                       # 设置thymeleaf严格校验
    encoding: UTF-8                         # 设置编码

  servlet:
    multipart: # 文件上传配置
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  task:
    scheduling: # 定时任务线程池配置
      pool:
        size: 2
  threads:
    virtual:
      enabled: true # 启用虚拟线程
