---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxd-gaming.
--- DateTime: 2024/7/28 下午2:49
---

TimeUnit = luajava.bindClass("java.util.concurrent.TimeUnit");

function urlPath(request)
    return request:getServletPath();
end

