db:
  sql:
    pgsql:
      debug: true
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.137.10:5432/game_log_1
      username: postgres
      password: test
      batchThreadSize: 5
