db:
  sql:
    pgsql:
      debug: true
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.28.0.26:5432/game_log_1
      username: postgres
      password: test
      batchThreadSize: 5
