--- 系统协调函数
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxd-gaming(無心道, 15388152619).
--- DateTime: 2024/10/21 19:49

LUA_Error = load("return _G.error")()
LUA_Print = load("return _G.print")()

function memory0()
    return collectgarbage("count")
end

function showmemory()
    local kb = collectgarbage("count")
    local mb = math.floor(kb / 1024)
    kb = math.floor(kb - mb * 1024)
    local gb = math.floor(mb / 1024);
    mb = math.floor(mb - gb * 1024)
    local str = ""
    if gb > 0 then
        str = str .. tostring(gb) .. " GB "
    end

    if mb > 0 or (gb > 0 and kb > 0) then
        str = str .. tostring(mb) .. " MB "
    end

    if kb > 0 then
        str = str .. tostring(kb) .. " KB "
    end

    print("Memory: " .. str, _VERSION)
end
