---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxd-gaming.
--- DateTime: 2024/7/27 下午11:36
---

function root(request, response, postBody)
    print("root")
    local s, e = pcall(function()
        responseUtil:responseObj(response, "root hello world")
    end)
    if not s then
        print("error:" .. debug.traceback(e))
    end
end

function index(request, response, postBody)
    --临时缓存设置300秒过期
    opsForValue:set("lua-dd", "dd", 300, TimeUnit.SECONDS);
    responseUtil:responseObj(response, "index lua -- dd")
end

function index3(request, response, postBody)
    local obj = { error = 0, msg = "index3 ok" };
    responseUtil:responseObj(response, obj)
end