db:
  sql:
    pgsql:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.28.0.26:5432/game_1
      username: postgres
      password: test
      scanPackage: "wxdgaming.spring.logcenter.entity"
