---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxd-gaming.
--- DateTime: 2024/7/27 下午11:36
---
function api_test(request, response, postBody)
    print("api_test")
    responseUtil:responseText(response, "api_test")
end

function paramsTest(p1, p2, p3, p4, p5, p6)
    print("p1 = " .. tostring(p1)
            .. "; p2 = " .. tostring(p2)
            .. "; p3 = " .. tostring(p3)
            .. "; p4 = " .. tostring(p4)
            .. "; p5 = " .. tostring(p5)
    )
    return { "ok", "ok" }
end