// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: InnerMessage.proto
// Protobuf Java Version: 4.28.2

package test.pojo.inner;

public final class InnerMessage {
  private InnerMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      InnerMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 服务器类型
   * </pre>
   *
   * Protobuf enum {@code Stype}
   */
  public enum Stype
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 游戏服
     * </pre>
     *
     * <code>GAME = 0;</code>
     */
    GAME(0),
    /**
     * <pre>
     * broker
     * </pre>
     *
     * <code>BROKER = 1;</code>
     */
    BROKER(1),
    /**
     * <pre>
     * 社交服
     * </pre>
     *
     * <code>CHAT = 2;</code>
     */
    CHAT(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Stype.class.getName());
    }
    /**
     * <pre>
     * 游戏服
     * </pre>
     *
     * <code>GAME = 0;</code>
     */
    public static final int GAME_VALUE = 0;
    /**
     * <pre>
     * broker
     * </pre>
     *
     * <code>BROKER = 1;</code>
     */
    public static final int BROKER_VALUE = 1;
    /**
     * <pre>
     * 社交服
     * </pre>
     *
     * <code>CHAT = 2;</code>
     */
    public static final int CHAT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Stype valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Stype forNumber(int value) {
      switch (value) {
        case 0: return GAME;
        case 1: return BROKER;
        case 2: return CHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Stype>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Stype> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Stype>() {
            public Stype findValueByNumber(int number) {
              return Stype.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return test.pojo.inner.InnerMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Stype[] VALUES = values();

    public static Stype valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Stype(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Stype)
  }

  public interface ReqRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     * @return The sid.
     */
    int getSid();

    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The enum numeric value on the wire for stype.
     */
    int getStypeValue();
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The stype.
     */
    test.pojo.inner.InnerMessage.Stype getStype();

    /**
     * <pre>
     * 外围ip
     * </pre>
     *
     * <code>string wlanIp = 3;</code>
     * @return The wlanIp.
     */
    java.lang.String getWlanIp();
    /**
     * <pre>
     * 外围ip
     * </pre>
     *
     * <code>string wlanIp = 3;</code>
     * @return The bytes for wlanIp.
     */
    com.google.protobuf.ByteString
        getWlanIpBytes();

    /**
     * <pre>
     * 内网ip
     * </pre>
     *
     * <code>string lanIp = 4;</code>
     * @return The lanIp.
     */
    java.lang.String getLanIp();
    /**
     * <pre>
     * 内网ip
     * </pre>
     *
     * <code>string lanIp = 4;</code>
     * @return The bytes for lanIp.
     */
    com.google.protobuf.ByteString
        getLanIpBytes();
  }
  /**
   * <pre>
   * 服务注册
   * </pre>
   *
   * Protobuf type {@code ReqRegister}
   */
  public static final class ReqRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqRegister)
      ReqRegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        ReqRegister.class.getName());
    }
    // Use ReqRegister.newBuilder() to construct.
    private ReqRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqRegister() {
      stype_ = 0;
      wlanIp_ = "";
      lanIp_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.pojo.inner.InnerMessage.internal_static_ReqRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.pojo.inner.InnerMessage.internal_static_ReqRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.pojo.inner.InnerMessage.ReqRegister.class, test.pojo.inner.InnerMessage.ReqRegister.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_ = 0;
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     * @return The sid.
     */
    @java.lang.Override
    public int getSid() {
      return sid_;
    }

    public static final int STYPE_FIELD_NUMBER = 2;
    private int stype_ = 0;
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The enum numeric value on the wire for stype.
     */
    @java.lang.Override public int getStypeValue() {
      return stype_;
    }
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The stype.
     */
    @java.lang.Override public test.pojo.inner.InnerMessage.Stype getStype() {
      test.pojo.inner.InnerMessage.Stype result = test.pojo.inner.InnerMessage.Stype.forNumber(stype_);
      return result == null ? test.pojo.inner.InnerMessage.Stype.UNRECOGNIZED : result;
    }

    public static final int WLANIP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object wlanIp_ = "";
    /**
     * <pre>
     * 外围ip
     * </pre>
     *
     * <code>string wlanIp = 3;</code>
     * @return The wlanIp.
     */
    @java.lang.Override
    public java.lang.String getWlanIp() {
      java.lang.Object ref = wlanIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wlanIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 外围ip
     * </pre>
     *
     * <code>string wlanIp = 3;</code>
     * @return The bytes for wlanIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWlanIpBytes() {
      java.lang.Object ref = wlanIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wlanIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANIP_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lanIp_ = "";
    /**
     * <pre>
     * 内网ip
     * </pre>
     *
     * <code>string lanIp = 4;</code>
     * @return The lanIp.
     */
    @java.lang.Override
    public java.lang.String getLanIp() {
      java.lang.Object ref = lanIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lanIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内网ip
     * </pre>
     *
     * <code>string lanIp = 4;</code>
     * @return The bytes for lanIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanIpBytes() {
      java.lang.Object ref = lanIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lanIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (stype_ != test.pojo.inner.InnerMessage.Stype.GAME.getNumber()) {
        output.writeEnum(2, stype_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(wlanIp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, wlanIp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lanIp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, lanIp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (stype_ != test.pojo.inner.InnerMessage.Stype.GAME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, stype_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(wlanIp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, wlanIp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lanIp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, lanIp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.pojo.inner.InnerMessage.ReqRegister)) {
        return super.equals(obj);
      }
      test.pojo.inner.InnerMessage.ReqRegister other = (test.pojo.inner.InnerMessage.ReqRegister) obj;

      if (getSid()
          != other.getSid()) return false;
      if (stype_ != other.stype_) return false;
      if (!getWlanIp()
          .equals(other.getWlanIp())) return false;
      if (!getLanIp()
          .equals(other.getLanIp())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + STYPE_FIELD_NUMBER;
      hash = (53 * hash) + stype_;
      hash = (37 * hash) + WLANIP_FIELD_NUMBER;
      hash = (53 * hash) + getWlanIp().hashCode();
      hash = (37 * hash) + LANIP_FIELD_NUMBER;
      hash = (53 * hash) + getLanIp().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static test.pojo.inner.InnerMessage.ReqRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static test.pojo.inner.InnerMessage.ReqRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.pojo.inner.InnerMessage.ReqRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.pojo.inner.InnerMessage.ReqRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务注册
     * </pre>
     *
     * Protobuf type {@code ReqRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqRegister)
        test.pojo.inner.InnerMessage.ReqRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.pojo.inner.InnerMessage.internal_static_ReqRegister_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.pojo.inner.InnerMessage.internal_static_ReqRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.pojo.inner.InnerMessage.ReqRegister.class, test.pojo.inner.InnerMessage.ReqRegister.Builder.class);
      }

      // Construct using test.pojo.inner.InnerMessage.ReqRegister.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sid_ = 0;
        stype_ = 0;
        wlanIp_ = "";
        lanIp_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.pojo.inner.InnerMessage.internal_static_ReqRegister_descriptor;
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ReqRegister getDefaultInstanceForType() {
        return test.pojo.inner.InnerMessage.ReqRegister.getDefaultInstance();
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ReqRegister build() {
        test.pojo.inner.InnerMessage.ReqRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ReqRegister buildPartial() {
        test.pojo.inner.InnerMessage.ReqRegister result = new test.pojo.inner.InnerMessage.ReqRegister(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(test.pojo.inner.InnerMessage.ReqRegister result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sid_ = sid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stype_ = stype_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.wlanIp_ = wlanIp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lanIp_ = lanIp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.pojo.inner.InnerMessage.ReqRegister) {
          return mergeFrom((test.pojo.inner.InnerMessage.ReqRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.pojo.inner.InnerMessage.ReqRegister other) {
        if (other == test.pojo.inner.InnerMessage.ReqRegister.getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.stype_ != 0) {
          setStypeValue(other.getStypeValue());
        }
        if (!other.getWlanIp().isEmpty()) {
          wlanIp_ = other.wlanIp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getLanIp().isEmpty()) {
          lanIp_ = other.lanIp_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                stype_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                wlanIp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                lanIp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sid_ ;
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @return The sid.
       */
      @java.lang.Override
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @param value The sid to set.
       * @return This builder for chaining.
       */
      public Builder setSid(int value) {

        sid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = 0;
        onChanged();
        return this;
      }

      private int stype_ = 0;
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return The enum numeric value on the wire for stype.
       */
      @java.lang.Override public int getStypeValue() {
        return stype_;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @param value The enum numeric value on the wire for stype to set.
       * @return This builder for chaining.
       */
      public Builder setStypeValue(int value) {
        stype_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return The stype.
       */
      @java.lang.Override
      public test.pojo.inner.InnerMessage.Stype getStype() {
        test.pojo.inner.InnerMessage.Stype result = test.pojo.inner.InnerMessage.Stype.forNumber(stype_);
        return result == null ? test.pojo.inner.InnerMessage.Stype.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @param value The stype to set.
       * @return This builder for chaining.
       */
      public Builder setStype(test.pojo.inner.InnerMessage.Stype value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        stype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object wlanIp_ = "";
      /**
       * <pre>
       * 外围ip
       * </pre>
       *
       * <code>string wlanIp = 3;</code>
       * @return The wlanIp.
       */
      public java.lang.String getWlanIp() {
        java.lang.Object ref = wlanIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wlanIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 外围ip
       * </pre>
       *
       * <code>string wlanIp = 3;</code>
       * @return The bytes for wlanIp.
       */
      public com.google.protobuf.ByteString
          getWlanIpBytes() {
        java.lang.Object ref = wlanIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wlanIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 外围ip
       * </pre>
       *
       * <code>string wlanIp = 3;</code>
       * @param value The wlanIp to set.
       * @return This builder for chaining.
       */
      public Builder setWlanIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        wlanIp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 外围ip
       * </pre>
       *
       * <code>string wlanIp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWlanIp() {
        wlanIp_ = getDefaultInstance().getWlanIp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 外围ip
       * </pre>
       *
       * <code>string wlanIp = 3;</code>
       * @param value The bytes for wlanIp to set.
       * @return This builder for chaining.
       */
      public Builder setWlanIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        wlanIp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object lanIp_ = "";
      /**
       * <pre>
       * 内网ip
       * </pre>
       *
       * <code>string lanIp = 4;</code>
       * @return The lanIp.
       */
      public java.lang.String getLanIp() {
        java.lang.Object ref = lanIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lanIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内网ip
       * </pre>
       *
       * <code>string lanIp = 4;</code>
       * @return The bytes for lanIp.
       */
      public com.google.protobuf.ByteString
          getLanIpBytes() {
        java.lang.Object ref = lanIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lanIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内网ip
       * </pre>
       *
       * <code>string lanIp = 4;</code>
       * @param value The lanIp to set.
       * @return This builder for chaining.
       */
      public Builder setLanIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lanIp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内网ip
       * </pre>
       *
       * <code>string lanIp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanIp() {
        lanIp_ = getDefaultInstance().getLanIp();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内网ip
       * </pre>
       *
       * <code>string lanIp = 4;</code>
       * @param value The bytes for lanIp to set.
       * @return This builder for chaining.
       */
      public Builder setLanIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lanIp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqRegister)
    }

    // @@protoc_insertion_point(class_scope:ReqRegister)
    private static final test.pojo.inner.InnerMessage.ReqRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.pojo.inner.InnerMessage.ReqRegister();
    }

    public static test.pojo.inner.InnerMessage.ReqRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRegister>
        PARSER = new com.google.protobuf.AbstractParser<ReqRegister>() {
      @java.lang.Override
      public ReqRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRegister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.pojo.inner.InnerMessage.ReqRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     * @return The sid.
     */
    int getSid();

    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The enum numeric value on the wire for stype.
     */
    int getStypeValue();
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The stype.
     */
    test.pojo.inner.InnerMessage.Stype getStype();
  }
  /**
   * <pre>
   * 服务注册
   * </pre>
   *
   * Protobuf type {@code ResRegister}
   */
  public static final class ResRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResRegister)
      ResRegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        ResRegister.class.getName());
    }
    // Use ResRegister.newBuilder() to construct.
    private ResRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResRegister() {
      stype_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.pojo.inner.InnerMessage.internal_static_ResRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.pojo.inner.InnerMessage.internal_static_ResRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.pojo.inner.InnerMessage.ResRegister.class, test.pojo.inner.InnerMessage.ResRegister.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_ = 0;
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     * @return The sid.
     */
    @java.lang.Override
    public int getSid() {
      return sid_;
    }

    public static final int STYPE_FIELD_NUMBER = 2;
    private int stype_ = 0;
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The enum numeric value on the wire for stype.
     */
    @java.lang.Override public int getStypeValue() {
      return stype_;
    }
    /**
     * <pre>
     * 服务器类型
     * </pre>
     *
     * <code>.Stype stype = 2;</code>
     * @return The stype.
     */
    @java.lang.Override public test.pojo.inner.InnerMessage.Stype getStype() {
      test.pojo.inner.InnerMessage.Stype result = test.pojo.inner.InnerMessage.Stype.forNumber(stype_);
      return result == null ? test.pojo.inner.InnerMessage.Stype.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (stype_ != test.pojo.inner.InnerMessage.Stype.GAME.getNumber()) {
        output.writeEnum(2, stype_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (stype_ != test.pojo.inner.InnerMessage.Stype.GAME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, stype_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.pojo.inner.InnerMessage.ResRegister)) {
        return super.equals(obj);
      }
      test.pojo.inner.InnerMessage.ResRegister other = (test.pojo.inner.InnerMessage.ResRegister) obj;

      if (getSid()
          != other.getSid()) return false;
      if (stype_ != other.stype_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + STYPE_FIELD_NUMBER;
      hash = (53 * hash) + stype_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static test.pojo.inner.InnerMessage.ResRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static test.pojo.inner.InnerMessage.ResRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.pojo.inner.InnerMessage.ResRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.pojo.inner.InnerMessage.ResRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务注册
     * </pre>
     *
     * Protobuf type {@code ResRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResRegister)
        test.pojo.inner.InnerMessage.ResRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.pojo.inner.InnerMessage.internal_static_ResRegister_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.pojo.inner.InnerMessage.internal_static_ResRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.pojo.inner.InnerMessage.ResRegister.class, test.pojo.inner.InnerMessage.ResRegister.Builder.class);
      }

      // Construct using test.pojo.inner.InnerMessage.ResRegister.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sid_ = 0;
        stype_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.pojo.inner.InnerMessage.internal_static_ResRegister_descriptor;
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ResRegister getDefaultInstanceForType() {
        return test.pojo.inner.InnerMessage.ResRegister.getDefaultInstance();
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ResRegister build() {
        test.pojo.inner.InnerMessage.ResRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.pojo.inner.InnerMessage.ResRegister buildPartial() {
        test.pojo.inner.InnerMessage.ResRegister result = new test.pojo.inner.InnerMessage.ResRegister(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(test.pojo.inner.InnerMessage.ResRegister result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sid_ = sid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stype_ = stype_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.pojo.inner.InnerMessage.ResRegister) {
          return mergeFrom((test.pojo.inner.InnerMessage.ResRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.pojo.inner.InnerMessage.ResRegister other) {
        if (other == test.pojo.inner.InnerMessage.ResRegister.getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.stype_ != 0) {
          setStypeValue(other.getStypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                stype_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sid_ ;
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @return The sid.
       */
      @java.lang.Override
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @param value The sid to set.
       * @return This builder for chaining.
       */
      public Builder setSid(int value) {

        sid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = 0;
        onChanged();
        return this;
      }

      private int stype_ = 0;
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return The enum numeric value on the wire for stype.
       */
      @java.lang.Override public int getStypeValue() {
        return stype_;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @param value The enum numeric value on the wire for stype to set.
       * @return This builder for chaining.
       */
      public Builder setStypeValue(int value) {
        stype_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return The stype.
       */
      @java.lang.Override
      public test.pojo.inner.InnerMessage.Stype getStype() {
        test.pojo.inner.InnerMessage.Stype result = test.pojo.inner.InnerMessage.Stype.forNumber(stype_);
        return result == null ? test.pojo.inner.InnerMessage.Stype.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @param value The stype to set.
       * @return This builder for chaining.
       */
      public Builder setStype(test.pojo.inner.InnerMessage.Stype value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        stype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器类型
       * </pre>
       *
       * <code>.Stype stype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stype_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResRegister)
    }

    // @@protoc_insertion_point(class_scope:ResRegister)
    private static final test.pojo.inner.InnerMessage.ResRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.pojo.inner.InnerMessage.ResRegister();
    }

    public static test.pojo.inner.InnerMessage.ResRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResRegister>
        PARSER = new com.google.protobuf.AbstractParser<ResRegister>() {
      @java.lang.Override
      public ResRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResRegister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.pojo.inner.InnerMessage.ResRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqRegister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqRegister_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResRegister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022InnerMessage.proto\"P\n\013ReqRegister\022\013\n\003s" +
      "id\030\001 \001(\005\022\025\n\005stype\030\002 \001(\0162\006.Stype\022\016\n\006wlanI" +
      "p\030\003 \001(\t\022\r\n\005lanIp\030\004 \001(\t\"1\n\013ResRegister\022\013\n" +
      "\003sid\030\001 \001(\005\022\025\n\005stype\030\002 \001(\0162\006.Stype*\'\n\005Sty" +
      "pe\022\010\n\004GAME\020\000\022\n\n\006BROKER\020\001\022\010\n\004CHAT\020\002B\021\n\017te" +
      "st.pojo.innerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReqRegister_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqRegister_descriptor,
        new java.lang.String[] { "Sid", "Stype", "WlanIp", "LanIp", });
    internal_static_ResRegister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResRegister_descriptor,
        new java.lang.String[] { "Sid", "Stype", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
