---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2024/12/26 16:47
---
Bootstrap = {}

---每次起服调用，仅执行一次
function onstart()

end

---每次lua文件加载结束调用的初始化，重载脚本也调用
function luainit()
    --- 查找全局函数的 onInit 函数调用 有缓存
    LuaScan.triggerTwoFunc("onInit")
end

---执行角色的登录事件
function onlogin(actor)
    --- 查找全局函数的 onLogin 函数调用 有缓存
    LuaScan.triggerTwoFunc("onLogin", actor)
end

---执行角色的进入地图事件
function onentermap(...)
    --- 查找全局函数的 onEnterMap 函数调用 有缓存
    LuaScan.triggerTwoFunc("onEnterMap", ...)
end