--- table 操作
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxdgaming.
--- DateTime: 2024/8/28 17:30
---


table = {}

function table.isArray(t)
    if type(t) ~= 'table' then
        return true
    end
    return false
end

function table.printTableJson(t)
    local json = ""
    for k, v in pairs(t) do
        if not (json == nil or json == "") then
            json = json .. ", "
        end
        if type(k) == "number" or type(k) == "boolean" then
            json = json .. tostring(k)
        else
            json = json .. tostring(v)
        end
        json = json .. ":"
        if type(v) == "number" or type(v) == "boolean" then
            json = json .. tostring(v)
        else
            json = json .. "\"" .. tostring(v) .. "\""
        end
    end
    local var = "{" .. json .. "}"
    print(var)
    return var
end

function table.printArrayJson(t)
    local json = ""
    pcall(function()
        for i, v in ipairs(t) do
            if not (json == nil or json == "") then
                json = json .. ", "
            end
            if type(v) == "number" or type(v) == "boolean" then
                json = json .. tostring(v)
            else
                json = json .. "\"" .. tostring(v) .. "\""
            end
        end
    end)
    local var = "[" .. json .. "]"
    print(var)
    return var
end

function table.print(t)
    if table.isArray(t) then
        return table.printArrayJson(t)
    else
        return table.printTableJson(t)
    end
end