core:
  executor:
    basic:
      coreSize: 2                        #默认线程池的核心线程数
      maxQueueSize: 10000                #队列超过就会打印异常
    logic:
      coreSize: 32                       #逻辑线程池
      maxQueueSize: 50000                #队列超过就会打印异常
    virtual:
      coreSize: 100                      #虚拟线程池
      maxQueueSize: 1500000              #队列超过就会打印异常
    scheduled:
      coreSize: 1
      maxQueueSize: 50000

boot:
  debug: true
  gid: 1
  sid: 1
  jwtKey: "123456789012345678901234567890123456789012345678901234567890"

server:
  port: 19800

spring:
  profiles:
    active: db,httpclient
